# Generated by Django 3.2.23 on 2023-11-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_auto_20231122_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
    ]
