# Generated by Django 3.2.23 on 2023-11-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_product_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeCaurosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200, null=True)),
                ('text2', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='profile.png', upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
