# Generated by Django 3.2.23 on 2023-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_auto_20231126_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecaurosel',
            name='btn_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
