# Generated by Django 3.2.23 on 2023-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_homecaurosel_btn_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=200, null=True)),
                ('heading2', models.CharField(max_length=200, null=True)),
                ('btn_text', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='profile.png', upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='trendy',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
